define LINUX_PRE_INSTALL_IMAGES_HOOK_FIXDTBLOCATION
		cp $(LINUX_ARCH_PATH)/boot/dts/amlogic/superbird_evt_512.dtb $(LINUX_ARCH_PATH)/boot
endef

LINUX_PRE_INSTALL_IMAGES_HOOKS += LINUX_PRE_INSTALL_IMAGES_HOOK_FIXDTBLOCATION

include $(sort $(wildcard $(BR2_EXTERNAL_SUPERDUPERBIRD_PATH)/package/*/*.mk))
